apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zivijo.fullname" . }}
  labels:
    {{- include "zivijo.labels" . | nindent 4 }}
data:
  narodeniny.csv: |
    {{ .Values.zivijo.csv_narodeniny_content }}
